{{ config(materialized='table') }}
SELECT VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDER_TABLE1.CUSTOMER_NAME FROM VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDERS_NEW INNER JOIN
VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDER_TABLE1 ON
VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDERS_NEW.CUSTOMER_NAME = VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDER_TABLE1.CUSTOMER_NAME 
WHERE VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDER_TABLE1.CUSTOMER_NAME = 'Claire Gute'
