{{ config(materialized='table') }}
select VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDER_TABLE1.CUSTOMER_NAME
from VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDERS_NEW
inner join VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDER_TABLE1
on  VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDERS_NEW.CUSTOMER_NAME =
VWE_DATABASE.X_POSTGRES_RDS_RAJSHRI.ORDER_TABLE1.CUSTOMER_NAME

