SELECT A.CUSTOMER_ID,A.CUSTOMER_NAME,A.STATUS,A.RATING,A.REMARKS_BY_UNHAPPY_CUSTOMERS AS REMARKS FROM  
VWE_DATABASE.PUBLIC.REVIEW_NEW as A
INNER JOIN VWE_DATABASE.PUBLIC.REVIEWS as B ON A.CUSTOMER_ID = B.CUSTOMER_ID
